---
- name: Check installed Microsoft update KBs with date and time
  hosts: windows
  gather_facts: no
  vars:
    kb_list:
      - KB5021234
      - KB5019980
      - KB5005565
  tasks:
    - name: Get installed updates with date and time
      win_shell: "wmic qfe get HotFixID, InstalledOn"
      register: updates

    - name: Process KB data
      set_fact:
        kb_info: >-
          {{
            updates.stdout_lines 
            | map('split', ' ')
            | selectattr(0, 'in', kb_list)
            | list
          }}

    - name: Save results to a CSV file
      copy:
        content: "{{ inventory_hostname }},{{ kb_info | map('join', ',') | join('\n') }}"
        dest: "/tmp/windows_updates_{{ inventory_hostname }}.csv"
      delegate_to: localhost
