- name: Convert CSV to XLSX and apply formatting
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run Python script to convert and format Excel
      ansible.builtin.command:
        cmd: python3 /opt/ansible/win_updates/convert_csv_to_xlsx.py

- name: Copy XLSX report to Dev host
  hosts: dev
  gather_facts: false

  tasks:
    - name: Copy Excel report to Dev host
      ansible.windows.win_copy:
        src: /opt/ansible/win_updates/converted_updates.xlsx
        dest: C:\Updates\converted_updates.xlsx
