- name: Install Windows Updates
  hosts: all
  tasks:
    - name: Apply Updates
      ansible.windows.win_updates:
        reboot: no #reboot will be handled in reboot_after_updates playbook
        state: installed
