- name: Reboot After Updates
  hosts: windows
  tasks:
    - name: Restart After Updates
      ansible.windows.win_reboot:
        reboot_timeout: 3600  #cancel the task if it runs longer than 1 hour
