---
- name: Check for Windows Updates
  hosts: windows
  gather_facts: false
  become: yes
  become_method: runas
  become_user: Administrator
  tasks:

    - name: Register NuGet provider silently
      ansible.windows.win_shell: |
        Install-PackageProvider -Name NuGet -Force -Scope CurrentUser

    - name: Ensure ImportExcel module is installed
      ansible.windows.win_shell: |
        if (-not (Get-Module -ListAvailable -Name ImportExcel)) {
          Write-Host "Installing ImportExcel..."
          Install-Module -Name ImportExcel -Scope CurrentUser -Force
          } else {
            Write-Host "ImportExcel module is already installed."
          }

    - name: Check ImportExcel module presence
      ansible.windows.win_shell: |
        Get-Module -ListAvailable -Name ImportExcel
      register: excel_check

    - name: Show Excel module check result
      debug:
        var: excel_check.stdout_lines

    - name: Create Updates folder
      ansible.windows.win_file:
        path: C:\Updates
        state: directory
        force: yes

    - name: Copy the PowerShell script to the target host
      ansible.windows.win_copy:
        src: check_updates_ps.ps1
        dest: C:\Updates\check_updates_ps.ps1

    - name: Execute the PowerShell script
      ansible.windows.win_shell: |
        PowerShell -ExecutionPolicy Bypass -File C:\Updates\check_updates_ps.ps1
      register: script_output

    - name: Fetch Excel book
      ansible.windows.win_fetch:
        src: C:\Updates\patch_report_{{ ansible_hostname }}.xlsx
        dest: /opt/ansible/win_updates/
        flat: yes
        mode: '0644'

    - name: Show script output
      debug:
        var: script_output.stdout_lines